# Generated by Django 5.2.5 on 2025-09-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='simulation_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='weatherfile_name',
        ),
    ]
