# Generated by Django 5.2.5 on 2025-09-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_first_name_record_simulation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='cooling_setpoint',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='floor_area',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='operation_schedule_type',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='reporting_interval',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='email',
            new_name='run_period',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='total_cooling_energy',
        ),
    ]
