# Generated by Django 5.2.5 on 2025-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_city_record_cooling_setpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='floor_area',
            new_name='cooling_schedule_type',
        ),
        migrations.AddField(
            model_name='record',
            name='envelope_properties',
            field=models.CharField(default=24, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='equipment_energy',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='eui',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='lighting_energy',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='peak_cooling_load',
            field=models.CharField(default='0', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='system_cop',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='cooling_setpoint',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='operation_schedule_type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='record',
            name='reporting_interval',
            field=models.CharField(max_length=20),
        ),
                migrations.AlterField(
            model_name='record',
            name='runperiod',
            field=models.CharField(max_length=100),
        ),
    ]
