# Generated by Django 5.2.5 on 2025-09-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_floor_area_record_cooling_schedule_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='runperiod',
            new_name='run_period',
        ),
    ]
